//
// © 2025 Sharon Aicler (saichler@gmail.com)
//
// Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package l8topo defines Protocol Buffer messages for network topology
// representation and visualization in the Layer 8 Ecosystem.
//
// This package provides data structures for:
//   - Network topology nodes (switches, routers, servers, etc.)
//   - Network links between nodes with direction and status
//   - Geographic and visual layout positioning
//   - Multiple layout algorithms for topology visualization

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: topology.proto

package l8topo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// L8TopologyLayout defines the available layout algorithms for
// arranging topology nodes in a visual representation.
type L8TopologyLayout int32

const (
	// Location uses geographic coordinates (longitude/latitude) for positioning.
	L8TopologyLayout_Location L8TopologyLayout = 0
	// Hierarchical arranges nodes in a tree-like structure with levels.
	L8TopologyLayout_Hierarchical L8TopologyLayout = 1
	// Circular places nodes in a circular arrangement.
	L8TopologyLayout_Circular L8TopologyLayout = 2
	// Radial arranges nodes in concentric circles from a center point.
	L8TopologyLayout_Radial L8TopologyLayout = 3
	// Force_Directed uses physics simulation to position nodes based on links.
	L8TopologyLayout_Force_Directed L8TopologyLayout = 4
)

// Enum value maps for L8TopologyLayout.
var (
	L8TopologyLayout_name = map[int32]string{
		0: "Location",
		1: "Hierarchical",
		2: "Circular",
		3: "Radial",
		4: "Force_Directed",
	}
	L8TopologyLayout_value = map[string]int32{
		"Location":       0,
		"Hierarchical":   1,
		"Circular":       2,
		"Radial":         3,
		"Force_Directed": 4,
	}
)

func (x L8TopologyLayout) Enum() *L8TopologyLayout {
	p := new(L8TopologyLayout)
	*p = x
	return p
}

func (x L8TopologyLayout) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8TopologyLayout) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_proto_enumTypes[0].Descriptor()
}

func (L8TopologyLayout) Type() protoreflect.EnumType {
	return &file_topology_proto_enumTypes[0]
}

func (x L8TopologyLayout) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8TopologyLayout.Descriptor instead.
func (L8TopologyLayout) EnumDescriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{0}
}

// L8TopologyNodeType classifies network devices by their function
// in the network infrastructure.
type L8TopologyNodeType int32

const (
	// Generic represents an unclassified or unknown device type.
	L8TopologyNodeType_Generic L8TopologyNodeType = 0
	// SWITCH represents a network switch for Layer 2 forwarding.
	L8TopologyNodeType_SWITCH L8TopologyNodeType = 1
	// ROUTER represents a router for Layer 3 routing.
	L8TopologyNodeType_ROUTER L8TopologyNodeType = 2
	// NETWORK_AGGREGATION represents an aggregation point in the network.
	L8TopologyNodeType_NETWORK_AGGREGATION L8TopologyNodeType = 3
	// FIREWALL represents a security device for traffic filtering.
	L8TopologyNodeType_FIREWALL L8TopologyNodeType = 4
	// LOAD_BALANCER represents a load balancing device.
	L8TopologyNodeType_LOAD_BALANCER L8TopologyNodeType = 5
	// ACCESS_POINT represents a wireless access point.
	L8TopologyNodeType_ACCESS_POINT L8TopologyNodeType = 6
	// SERVER represents a compute server or host.
	L8TopologyNodeType_SERVER L8TopologyNodeType = 7
	// STORAGE represents a storage device or array.
	L8TopologyNodeType_STORAGE L8TopologyNodeType = 8
	// GATEWAY represents a network gateway device.
	L8TopologyNodeType_GATEWAY L8TopologyNodeType = 9
)

// Enum value maps for L8TopologyNodeType.
var (
	L8TopologyNodeType_name = map[int32]string{
		0: "Generic",
		1: "SWITCH",
		2: "ROUTER",
		3: "NETWORK_AGGREGATION",
		4: "FIREWALL",
		5: "LOAD_BALANCER",
		6: "ACCESS_POINT",
		7: "SERVER",
		8: "STORAGE",
		9: "GATEWAY",
	}
	L8TopologyNodeType_value = map[string]int32{
		"Generic":             0,
		"SWITCH":              1,
		"ROUTER":              2,
		"NETWORK_AGGREGATION": 3,
		"FIREWALL":            4,
		"LOAD_BALANCER":       5,
		"ACCESS_POINT":        6,
		"SERVER":              7,
		"STORAGE":             8,
		"GATEWAY":             9,
	}
)

func (x L8TopologyNodeType) Enum() *L8TopologyNodeType {
	p := new(L8TopologyNodeType)
	*p = x
	return p
}

func (x L8TopologyNodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8TopologyNodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_proto_enumTypes[1].Descriptor()
}

func (L8TopologyNodeType) Type() protoreflect.EnumType {
	return &file_topology_proto_enumTypes[1]
}

func (x L8TopologyNodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8TopologyNodeType.Descriptor instead.
func (L8TopologyNodeType) EnumDescriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{1}
}

// L8topologyLinkDirection indicates the traffic flow direction of a link.
type L8TopologyLinkDirection int32

const (
	// InvalidDirection represents an unset or invalid direction.
	L8TopologyLinkDirection_InvalidDirection L8TopologyLinkDirection = 0
	// AsideToZside indicates traffic flows from the A-side to the Z-side.
	L8TopologyLinkDirection_AsideToZside L8TopologyLinkDirection = 1
	// ZsideToAside indicates traffic flows from the Z-side to the A-side.
	L8TopologyLinkDirection_ZsideToAside L8TopologyLinkDirection = 2
	// Bidirectional indicates traffic flows in both directions.
	L8TopologyLinkDirection_Bidirectional L8TopologyLinkDirection = 3
)

// Enum value maps for L8TopologyLinkDirection.
var (
	L8TopologyLinkDirection_name = map[int32]string{
		0: "InvalidDirection",
		1: "AsideToZside",
		2: "ZsideToAside",
		3: "Bidirectional",
	}
	L8TopologyLinkDirection_value = map[string]int32{
		"InvalidDirection": 0,
		"AsideToZside":     1,
		"ZsideToAside":     2,
		"Bidirectional":    3,
	}
)

func (x L8TopologyLinkDirection) Enum() *L8TopologyLinkDirection {
	p := new(L8TopologyLinkDirection)
	*p = x
	return p
}

func (x L8TopologyLinkDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8TopologyLinkDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_proto_enumTypes[2].Descriptor()
}

func (L8TopologyLinkDirection) Type() protoreflect.EnumType {
	return &file_topology_proto_enumTypes[2]
}

func (x L8TopologyLinkDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8TopologyLinkDirection.Descriptor instead.
func (L8TopologyLinkDirection) EnumDescriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{2}
}

// L8TopologyLinkStatus represents the operational state of a network link.
type L8TopologyLinkStatus int32

const (
	// InvalidStatus represents an unset or invalid status.
	L8TopologyLinkStatus_InvalidStatus L8TopologyLinkStatus = 0
	// Up indicates the link is fully operational.
	L8TopologyLinkStatus_Up L8TopologyLinkStatus = 1
	// Down indicates the link is not operational.
	L8TopologyLinkStatus_Down L8TopologyLinkStatus = 2
	// Partial indicates the link is partially operational (degraded).
	L8TopologyLinkStatus_Partial L8TopologyLinkStatus = 3
)

// Enum value maps for L8TopologyLinkStatus.
var (
	L8TopologyLinkStatus_name = map[int32]string{
		0: "InvalidStatus",
		1: "Up",
		2: "Down",
		3: "Partial",
	}
	L8TopologyLinkStatus_value = map[string]int32{
		"InvalidStatus": 0,
		"Up":            1,
		"Down":          2,
		"Partial":       3,
	}
)

func (x L8TopologyLinkStatus) Enum() *L8TopologyLinkStatus {
	p := new(L8TopologyLinkStatus)
	*p = x
	return p
}

func (x L8TopologyLinkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (L8TopologyLinkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_proto_enumTypes[3].Descriptor()
}

func (L8TopologyLinkStatus) Type() protoreflect.EnumType {
	return &file_topology_proto_enumTypes[3]
}

func (x L8TopologyLinkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use L8TopologyLinkStatus.Descriptor instead.
func (L8TopologyLinkStatus) EnumDescriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{3}
}

// L8TopologyQuery represents a request for topology data with layout
// preferences and viewport boundaries.
type L8TopologyQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// layout specifies which layout algorithm to use for node positioning.
	Layout L8TopologyLayout `protobuf:"varint,1,opt,name=layout,proto3,enum=l8topo.L8TopologyLayout" json:"layout,omitempty"`
	// x is the left boundary of the viewport in SVG coordinates.
	X float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	// y is the top boundary of the viewport in SVG coordinates.
	Y float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	// x1 is the right boundary of the viewport in SVG coordinates.
	X1 float32 `protobuf:"fixed32,4,opt,name=x1,proto3" json:"x1,omitempty"`
	// y1 is the bottom boundary of the viewport in SVG coordinates.
	Y1 float32 `protobuf:"fixed32,5,opt,name=y1,proto3" json:"y1,omitempty"`
}

func (x *L8TopologyQuery) Reset() {
	*x = L8TopologyQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TopologyQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TopologyQuery) ProtoMessage() {}

func (x *L8TopologyQuery) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TopologyQuery.ProtoReflect.Descriptor instead.
func (*L8TopologyQuery) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{0}
}

func (x *L8TopologyQuery) GetLayout() L8TopologyLayout {
	if x != nil {
		return x.Layout
	}
	return L8TopologyLayout_Location
}

func (x *L8TopologyQuery) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *L8TopologyQuery) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *L8TopologyQuery) GetX1() float32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *L8TopologyQuery) GetY1() float32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

// L8Topology is the main container for a complete network topology,
// holding all nodes, links, and location data.
type L8Topology struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the identifier for this topology instance.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// nodes maps node IDs to their L8TopologyNode definitions.
	Nodes map[string]*L8TopologyNode `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// links maps link IDs to their L8TopologyLink definitions.
	Links map[string]*L8TopologyLink `protobuf:"bytes,3,rep,name=links,proto3" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// locations maps location names to their L8TopologyLocation definitions.
	Locations map[string]*L8TopologyLocation `protobuf:"bytes,4,rep,name=locations,proto3" json:"locations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *L8Topology) Reset() {
	*x = L8Topology{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8Topology) ProtoMessage() {}

func (x *L8Topology) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8Topology.ProtoReflect.Descriptor instead.
func (*L8Topology) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{1}
}

func (x *L8Topology) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8Topology) GetNodes() map[string]*L8TopologyNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *L8Topology) GetLinks() map[string]*L8TopologyLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *L8Topology) GetLocations() map[string]*L8TopologyLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

// L8TopologyNode represents a single node (device) in the network topology.
type L8TopologyNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// node_id is the unique identifier for this node.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// name is the human-readable display name for this node.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// location references the L8TopologyLocation where this node resides.
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// count indicates how many instances this node represents (for aggregation).
	Count int32 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	// type classifies the node by its network function.
	Type L8TopologyNodeType `protobuf:"varint,5,opt,name=type,proto3,enum=l8topo.L8TopologyNodeType" json:"type,omitempty"`
	// alarm_count is the number of active alarms on this node (populated by alarm overlay).
	AlarmCount int32 `protobuf:"varint,6,opt,name=alarm_count,json=alarmCount,proto3" json:"alarm_count,omitempty"`
	// highest_alarm_severity is the highest alarm severity value on this node (0=none, 1-5 maps to severity levels).
	HighestAlarmSeverity int32 `protobuf:"varint,7,opt,name=highest_alarm_severity,json=highestAlarmSeverity,proto3" json:"highest_alarm_severity,omitempty"`
}

func (x *L8TopologyNode) Reset() {
	*x = L8TopologyNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TopologyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TopologyNode) ProtoMessage() {}

func (x *L8TopologyNode) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TopologyNode.ProtoReflect.Descriptor instead.
func (*L8TopologyNode) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{2}
}

func (x *L8TopologyNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *L8TopologyNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8TopologyNode) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *L8TopologyNode) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *L8TopologyNode) GetType() L8TopologyNodeType {
	if x != nil {
		return x.Type
	}
	return L8TopologyNodeType_Generic
}

func (x *L8TopologyNode) GetAlarmCount() int32 {
	if x != nil {
		return x.AlarmCount
	}
	return 0
}

func (x *L8TopologyNode) GetHighestAlarmSeverity() int32 {
	if x != nil {
		return x.HighestAlarmSeverity
	}
	return 0
}

// L8TopologyLocation defines both geographic and visual coordinates
// for positioning nodes in the topology view.
type L8TopologyLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// location is the unique identifier/name for this location.
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// longitude is the geographic longitude coordinate (for map-based layouts).
	Longitude float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// latitude is the geographic latitude coordinate (for map-based layouts).
	Latitude float32 `protobuf:"fixed32,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// svg_x is the computed X coordinate for SVG rendering.
	SvgX float32 `protobuf:"fixed32,4,opt,name=svg_x,json=svgX,proto3" json:"svg_x,omitempty"`
	// svg_y is the computed Y coordinate for SVG rendering.
	SvgY float32 `protobuf:"fixed32,5,opt,name=svg_y,json=svgY,proto3" json:"svg_y,omitempty"`
}

func (x *L8TopologyLocation) Reset() {
	*x = L8TopologyLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TopologyLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TopologyLocation) ProtoMessage() {}

func (x *L8TopologyLocation) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TopologyLocation.ProtoReflect.Descriptor instead.
func (*L8TopologyLocation) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{3}
}

func (x *L8TopologyLocation) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *L8TopologyLocation) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *L8TopologyLocation) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *L8TopologyLocation) GetSvgX() float32 {
	if x != nil {
		return x.SvgX
	}
	return 0
}

func (x *L8TopologyLocation) GetSvgY() float32 {
	if x != nil {
		return x.SvgY
	}
	return 0
}

// L8TopologyLink represents a connection between two nodes in the topology.
type L8TopologyLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// link_id is the unique identifier for this link.
	LinkId string `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	// aside is the node_id of the first endpoint (A-side).
	Aside string `protobuf:"bytes,2,opt,name=aside,proto3" json:"aside,omitempty"`
	// zside is the node_id of the second endpoint (Z-side).
	Zside string `protobuf:"bytes,3,opt,name=zside,proto3" json:"zside,omitempty"`
	// direction indicates the traffic flow direction of this link.
	Direction L8TopologyLinkDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=l8topo.L8TopologyLinkDirection" json:"direction,omitempty"`
	// status indicates the current operational state of this link.
	Status L8TopologyLinkStatus `protobuf:"varint,5,opt,name=status,proto3,enum=l8topo.L8TopologyLinkStatus" json:"status,omitempty"`
	// alarm_count is the number of active alarms on this link (populated by alarm overlay).
	AlarmCount int32 `protobuf:"varint,6,opt,name=alarm_count,json=alarmCount,proto3" json:"alarm_count,omitempty"`
	// highest_alarm_severity is the highest alarm severity value on this link (0=none, 1-5 maps to severity levels).
	HighestAlarmSeverity int32 `protobuf:"varint,7,opt,name=highest_alarm_severity,json=highestAlarmSeverity,proto3" json:"highest_alarm_severity,omitempty"`
}

func (x *L8TopologyLink) Reset() {
	*x = L8TopologyLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TopologyLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TopologyLink) ProtoMessage() {}

func (x *L8TopologyLink) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TopologyLink.ProtoReflect.Descriptor instead.
func (*L8TopologyLink) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{4}
}

func (x *L8TopologyLink) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *L8TopologyLink) GetAside() string {
	if x != nil {
		return x.Aside
	}
	return ""
}

func (x *L8TopologyLink) GetZside() string {
	if x != nil {
		return x.Zside
	}
	return ""
}

func (x *L8TopologyLink) GetDirection() L8TopologyLinkDirection {
	if x != nil {
		return x.Direction
	}
	return L8TopologyLinkDirection_InvalidDirection
}

func (x *L8TopologyLink) GetStatus() L8TopologyLinkStatus {
	if x != nil {
		return x.Status
	}
	return L8TopologyLinkStatus_InvalidStatus
}

func (x *L8TopologyLink) GetAlarmCount() int32 {
	if x != nil {
		return x.AlarmCount
	}
	return 0
}

func (x *L8TopologyLink) GetHighestAlarmSeverity() int32 {
	if x != nil {
		return x.HighestAlarmSeverity
	}
	return 0
}

// L8TopologyMetadataList is a collection of topology metadata entries.
type L8TopologyMetadataList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// list contains the topology metadata entries.
	List []*L8TopologyMetadata `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *L8TopologyMetadataList) Reset() {
	*x = L8TopologyMetadataList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TopologyMetadataList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TopologyMetadataList) ProtoMessage() {}

func (x *L8TopologyMetadataList) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TopologyMetadataList.ProtoReflect.Descriptor instead.
func (*L8TopologyMetadataList) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{5}
}

func (x *L8TopologyMetadataList) GetList() []*L8TopologyMetadata {
	if x != nil {
		return x.List
	}
	return nil
}

// L8TopologyMetadata provides metadata about a topology service instance.
type L8TopologyMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name is the display name for this topology.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// serviceName is the internal service identifier.
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	// serviceArea is the numeric area/region code for the service.
	ServiceArea int32 `protobuf:"varint,3,opt,name=serviceArea,proto3" json:"serviceArea,omitempty"`
}

func (x *L8TopologyMetadata) Reset() {
	*x = L8TopologyMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *L8TopologyMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L8TopologyMetadata) ProtoMessage() {}

func (x *L8TopologyMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_topology_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L8TopologyMetadata.ProtoReflect.Descriptor instead.
func (*L8TopologyMetadata) Descriptor() ([]byte, []int) {
	return file_topology_proto_rawDescGZIP(), []int{6}
}

func (x *L8TopologyMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *L8TopologyMetadata) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *L8TopologyMetadata) GetServiceArea() int32 {
	if x != nil {
		return x.ServiceArea
	}
	return 0
}

var File_topology_proto protoreflect.FileDescriptor

var file_topology_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x22, 0x7f, 0x0a, 0x0f, 0x4c, 0x38, 0x54, 0x6f,
	0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x30, 0x0a, 0x06, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6c, 0x38,
	0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x78, 0x31, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x78, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x79, 0x31, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x79, 0x31, 0x22, 0xc9, 0x03, 0x0a, 0x0a, 0x4c, 0x38,
	0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6c, 0x38,
	0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x33, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x3f, 0x0a, 0x09, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6c, 0x38, 0x74, 0x6f,
	0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x2e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x50, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e,
	0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x50, 0x0a, 0x0a, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70,
	0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4c, 0x69, 0x6e, 0x6b,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x58, 0x0a, 0x0e, 0x4c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x30, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xf6, 0x01, 0x0a, 0x0e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c,
	0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x61, 0x72, 0x6d,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6c,
	0x61, 0x72, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x16, 0x68, 0x69, 0x67, 0x68,
	0x65, 0x73, 0x74, 0x5f, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69,
	0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x14, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73,
	0x74, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x22, 0x94,
	0x01, 0x0a, 0x12, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x13, 0x0a, 0x05, 0x73,
	0x76, 0x67, 0x5f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x76, 0x67, 0x58,
	0x12, 0x13, 0x0a, 0x05, 0x73, 0x76, 0x67, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x73, 0x76, 0x67, 0x59, 0x22, 0xa1, 0x02, 0x0a, 0x0e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x69, 0x6e, 0x6b,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x69, 0x6e, 0x6b, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x69, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x61, 0x73, 0x69, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x7a, 0x73, 0x69, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x7a, 0x73, 0x69, 0x64, 0x65, 0x12, 0x3d, 0x0a,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1f, 0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x74, 0x6f, 0x70, 0x6f,
	0x6c, 0x6f, 0x67, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6c,
	0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79,
	0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x34, 0x0a, 0x16, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x5f, 0x61,
	0x6c, 0x61, 0x72, 0x6d, 0x5f, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x14, 0x68, 0x69, 0x67, 0x68, 0x65, 0x73, 0x74, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x22, 0x48, 0x0a, 0x16, 0x4c, 0x38, 0x54,
	0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x2e, 0x4c, 0x38, 0x54, 0x6f, 0x70,
	0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x12, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67,
	0x79, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x2a, 0x60, 0x0a, 0x10, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x48, 0x69, 0x65, 0x72, 0x61, 0x72, 0x63, 0x68, 0x69,
	0x63, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x69, 0x72, 0x63, 0x75, 0x6c, 0x61,
	0x72, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x61, 0x64, 0x69, 0x61, 0x6c, 0x10, 0x03, 0x12,
	0x12, 0x0a, 0x0e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x10, 0x04, 0x2a, 0xab, 0x01, 0x0a, 0x12, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x6c, 0x6f,
	0x67, 0x79, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x69, 0x63, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x57, 0x49, 0x54, 0x43,
	0x48, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12,
	0x17, 0x0a, 0x13, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x41, 0x47, 0x47, 0x52, 0x45,
	0x47, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x52, 0x45,
	0x57, 0x41, 0x4c, 0x4c, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x4f, 0x41, 0x44, 0x5f, 0x42,
	0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x52, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x43, 0x43,
	0x45, 0x53, 0x53, 0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41,
	0x47, 0x45, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x47, 0x41, 0x54, 0x45, 0x57, 0x41, 0x59, 0x10,
	0x09, 0x2a, 0x66, 0x0a, 0x17, 0x4c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4c,
	0x69, 0x6e, 0x6b, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x10,
	0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x73, 0x69, 0x64, 0x65, 0x54, 0x6f, 0x5a, 0x73, 0x69,
	0x64, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x5a, 0x73, 0x69, 0x64, 0x65, 0x54, 0x6f, 0x41,
	0x73, 0x69, 0x64, 0x65, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x69, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x10, 0x03, 0x2a, 0x48, 0x0a, 0x14, 0x4c, 0x38, 0x54,
	0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x70, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x6f, 0x77, 0x6e, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61,
	0x6c, 0x10, 0x03, 0x42, 0x2c, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x6c, 0x38, 0x74, 0x6f, 0x70, 0x6f, 0x42, 0x06, 0x4c, 0x38, 0x54, 0x6f, 0x70, 0x6f, 0x50,
	0x01, 0x5a, 0x0e, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x6c, 0x38, 0x74, 0x6f, 0x70,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_topology_proto_rawDescOnce sync.Once
	file_topology_proto_rawDescData = file_topology_proto_rawDesc
)

func file_topology_proto_rawDescGZIP() []byte {
	file_topology_proto_rawDescOnce.Do(func() {
		file_topology_proto_rawDescData = protoimpl.X.CompressGZIP(file_topology_proto_rawDescData)
	})
	return file_topology_proto_rawDescData
}

var file_topology_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_topology_proto_goTypes = []interface{}{
	(L8TopologyLayout)(0),          // 0: l8topo.L8TopologyLayout
	(L8TopologyNodeType)(0),        // 1: l8topo.L8TopologyNodeType
	(L8TopologyLinkDirection)(0),   // 2: l8topo.L8topologyLinkDirection
	(L8TopologyLinkStatus)(0),      // 3: l8topo.L8TopologyLinkStatus
	(*L8TopologyQuery)(nil),        // 4: l8topo.L8TopologyQuery
	(*L8Topology)(nil),             // 5: l8topo.L8Topology
	(*L8TopologyNode)(nil),         // 6: l8topo.L8TopologyNode
	(*L8TopologyLocation)(nil),     // 7: l8topo.L8TopologyLocation
	(*L8TopologyLink)(nil),         // 8: l8topo.L8TopologyLink
	(*L8TopologyMetadataList)(nil), // 9: l8topo.L8TopologyMetadataList
	(*L8TopologyMetadata)(nil),     // 10: l8topo.L8TopologyMetadata
	nil,                            // 11: l8topo.L8Topology.NodesEntry
	nil,                            // 12: l8topo.L8Topology.LinksEntry
	nil,                            // 13: l8topo.L8Topology.LocationsEntry
}
var file_topology_proto_depIdxs = []int32{
	0,  // 0: l8topo.L8TopologyQuery.layout:type_name -> l8topo.L8TopologyLayout
	11, // 1: l8topo.L8Topology.nodes:type_name -> l8topo.L8Topology.NodesEntry
	12, // 2: l8topo.L8Topology.links:type_name -> l8topo.L8Topology.LinksEntry
	13, // 3: l8topo.L8Topology.locations:type_name -> l8topo.L8Topology.LocationsEntry
	1,  // 4: l8topo.L8TopologyNode.type:type_name -> l8topo.L8TopologyNodeType
	2,  // 5: l8topo.L8TopologyLink.direction:type_name -> l8topo.L8topologyLinkDirection
	3,  // 6: l8topo.L8TopologyLink.status:type_name -> l8topo.L8TopologyLinkStatus
	10, // 7: l8topo.L8TopologyMetadataList.list:type_name -> l8topo.L8TopologyMetadata
	6,  // 8: l8topo.L8Topology.NodesEntry.value:type_name -> l8topo.L8TopologyNode
	8,  // 9: l8topo.L8Topology.LinksEntry.value:type_name -> l8topo.L8TopologyLink
	7,  // 10: l8topo.L8Topology.LocationsEntry.value:type_name -> l8topo.L8TopologyLocation
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_topology_proto_init() }
func file_topology_proto_init() {
	if File_topology_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_topology_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TopologyQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8Topology); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TopologyNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TopologyLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TopologyLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TopologyMetadataList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_topology_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*L8TopologyMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topology_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topology_proto_goTypes,
		DependencyIndexes: file_topology_proto_depIdxs,
		EnumInfos:         file_topology_proto_enumTypes,
		MessageInfos:      file_topology_proto_msgTypes,
	}.Build()
	File_topology_proto = out.File
	file_topology_proto_rawDesc = nil
	file_topology_proto_goTypes = nil
	file_topology_proto_depIdxs = nil
}
